# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  version:  # id of input
    description: "What version is the python package you'd like to build?"
    required: true
    default: '1.0.0'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
